/**
 * planetary-ship.js
 * The Strawberry Milk delivery ship: it patrols the hub constellation and, when a
 * planet is chosen, flies down and perches on its surface before navigation.
 *
 * The hull comes from `src/spaceship-model.js`, generated by
 * scripts/build-spaceship-model.mjs. It arrives normalised with its longest axis at
 * 1 and its base sitting on y = 0, which is what makes the touchdown pose a matter
 * of pointing local +Y along the surface normal.
 */

import * as THREE from 'three';

export const SHIP_LENGTH = 16; // world units; a selected planet's body spans 27-32
const PATROL_SECONDS = 30;   // one lap around the constellation
const ORBIT_SECONDS = 26;    // one lap around a focused planet
const ORBIT_FACTOR = 1.5;    // orbit radius as a multiple of the planet's body radius
const ORBIT_TILT = 0.31;     // radians; keeps the ring from reading perfectly edge-on
const SURFACE_INSET = 0.06;  // fraction of hull length sunk in, so a flat hull hugs a sphere
const FLY_MS = 900;          // cruise towards the planet
const TOUCHDOWN_MS = 1350;   // final descent
const HOLD_MS = 1500;        // beat on the surface before navigating

const UP = new THREE.Vector3(0, 1, 0);
const FORWARD = new THREE.Vector3(0, 0, 1);
const FALLBACK_LAYOUT = { spreadX: 128, spreadY: 190 };

// The sunflower is a flat bloom rather than a ball, so its standable/visible radius is
// the petal rim (radius*2.05) instead of the core.
export function planetFootprint(planet, scale) {
  return planet.radius * (planet.isSunflower ? 2.05 : 1) * scale;
}

// Shared with the hub so the camera can frame the ring the ship flies on.
export function orbitRadiusFor(planet, scale) {
  return planetFootprint(planet, scale) * ORBIT_FACTOR + SHIP_LENGTH * 0.8;
}

// Multiplied into the photographic base colour, so these read as liveries.
const TINTS = [0xffffff, 0xffd9e6, 0xd9f2ff, 0xe9ffd9, 0xfff0d9];

function hashString(value) {
  let h = 2166136261;
  for (let i = 0; i < value.length; i++) {
    h ^= value.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function variantFor(planetId) {
  let seed = hashString(planetId || 'cosmos');
  const rng = () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };

  return {
    tint: TINTS[Math.floor(rng() * TINTS.length)],
    scale: 0.92 + rng() * 0.16,
    emissive: 0.85 + rng() * 0.5,
  };
}

const easeInOutCubic = (t) => (t < 0.5 ? 4 * t * t * t : 1 - ((-2 * t + 2) ** 3) / 2);
const easeOutCubic = (t) => 1 - (1 - t) ** 3;

function quadBezier(a, c, b, t) {
  const inv = 1 - t;
  return a.clone()
    .multiplyScalar(inv * inv)
    .addScaledVector(c, 2 * inv * t)
    .addScaledVector(b, t * t);
}

export class PlanetaryShip {
  static async create({ scene, reducedMotion = false, layout }) {
    const { SPACESHIP_DATA } = await import('../spaceship-model.js');
    return new PlanetaryShip({ scene, data: SPACESHIP_DATA, reducedMotion, layout });
  }

  constructor({ scene, data, reducedMotion, layout }) {
    this.data = data;
    this.reducedMotion = reducedMotion;
    this.layout = layout || FALLBACK_LAYOUT;

    this.startAngle = Math.random() * Math.PI * 2;
    this.landing = null;
    this.focus = null;

    this.targetScale = SHIP_LENGTH;
    this.currentScale = SHIP_LENGTH;
    this.targetTint = new THREE.Color(0xffffff);
    this.currentTint = new THREE.Color(0xffffff);
    this.targetEmissive = 1;
    this.currentEmissive = 1;

    this._basis = new THREE.Matrix4();
    this._quaternion = new THREE.Quaternion();

    this.heading = new THREE.Vector3(0, 0, 1);

    this.material = this.buildMaterial(data);
    this.mesh = new THREE.Mesh(this.buildGeometry(data), this.material);
    this.mesh.scale.setScalar(this.currentScale);

    // A generous invisible sphere: the hull is only ~36px at overview distance, far too
    // small to hit reliably with a thumb.
    this.hitMesh = new THREE.Mesh(
      new THREE.SphereGeometry(SHIP_LENGTH * 0.62, 12, 8),
      new THREE.MeshBasicMaterial({ visible: false }),
    );
    this.hitMesh.userData.ship = this;

    this.group = new THREE.Group();
    this.group.add(this.mesh);
    this.group.add(this.hitMesh);
    this.group.position.set(this.layout.spreadX, 0, this.layout.spreadX * 0.45);
    scene.add(this.group);
  }

  hullHeight() {
    return (this.data.size ? this.data.size[1] : 0.57) * this.currentScale;
  }

  // Local +Y is the hull's up axis, so it points away from whatever it is perched on.
  worldUp(target) {
    return target.set(0, 1, 0).applyQuaternion(this.group.quaternion);
  }

  worldCenter(target) {
    return this.worldUp(target).multiplyScalar(this.hullHeight() * 0.5).add(this.group.position);
  }

  worldLabelAnchor(target) {
    return this.worldUp(target).multiplyScalar(this.hullHeight() * 1.45).add(this.group.position);
  }

  setVisible(visible) {
    this.mesh.visible = visible;
  }

  buildGeometry(data) {
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.Float32BufferAttribute(data.positions, 3));
    geometry.setAttribute('normal', new THREE.Float32BufferAttribute(data.normals, 3));
    geometry.setAttribute('uv', new THREE.Float32BufferAttribute(data.uvs, 2));
    // Without tangents the normal map lights the hull from the wrong direction.
    if (data.tangents) {
      geometry.setAttribute('tangent', new THREE.Float32BufferAttribute(data.tangents, 4));
    }
    geometry.setIndex(data.indices);
    return geometry;
  }

  buildMaterial(data) {
    const loader = new THREE.TextureLoader();

    const baseColor = loader.load(data.textureDataUrl);
    baseColor.colorSpace = THREE.SRGBColorSpace;
    const emissive = loader.load(data.emissiveDataUrl);
    emissive.colorSpace = THREE.SRGBColorSpace;
    // Normal and ORM stay in the default linear space on purpose.
    const normalMap = loader.load(data.normalDataUrl);
    const orm = loader.load(data.metalRoughDataUrl);

    // The hull's uvs run a hair past 1, so clamping would smear the edge texel.
    for (const texture of [baseColor, emissive, normalMap, orm]) {
      texture.wrapS = THREE.RepeatWrapping;
      texture.wrapT = THREE.RepeatWrapping;
      // glTF uvs put the origin at the top-left corner; three.js flips by default, which
      // would sample all four maps mirrored.
      texture.flipY = false;
    }

    this.textures = { baseColor, emissive, normalMap, orm };

    return new THREE.MeshStandardMaterial({
      map: baseColor,
      normalMap,
      emissiveMap: emissive,
      metalnessMap: orm,
      roughnessMap: orm,
      emissive: new THREE.Color(0xffffff),
      emissiveIntensity: this.currentEmissive,
      // The hub has no environment map and an unlit metal reads as black. The asset's
      // metalness averages 0.42, so the scalar scales it into painted-hull territory.
      metalness: 0.35,
      roughness: 1,
      side: THREE.DoubleSide,
    });
  }

  setLayout(layout) {
    if (layout) this.layout = layout;
  }

  setVariantFor(planetId) {
    const variant = variantFor(planetId);
    this.targetTint.setHex(variant.tint);
    this.targetScale = SHIP_LENGTH * variant.scale;
    this.targetEmissive = variant.emissive;
  }

  orient(forward, up, factor = 1) {
    if (forward.lengthSq() < 1e-8) return;
    const xAxis = forward.clone().normalize();
    this.heading.copy(xAxis);
    let yAxis = up.clone().addScaledVector(xAxis, -up.dot(xAxis));
    if (yAxis.lengthSq() < 1e-6) {
      // The reference is parallel to the heading, so this basis would collapse and the
      // hull would flip. Fall back to an axis that cannot be parallel to it.
      const reference = Math.abs(xAxis.y) < 0.9 ? UP : FORWARD;
      yAxis = reference.clone().addScaledVector(xAxis, -reference.dot(xAxis));
    }
    yAxis.normalize();
    const zAxis = new THREE.Vector3().crossVectors(xAxis, yAxis);

    this._basis.makeBasis(xAxis, yAxis, zAxis);
    this._quaternion.setFromRotationMatrix(this._basis);
    if (factor >= 1) this.group.quaternion.copy(this._quaternion);
    else this.group.quaternion.slerp(this._quaternion, factor);
  }

  update(time) {
    if (this.landing) {
      this.stepLanding(performance.now());
    } else if (this.focus) {
      this.stepOrbit(time);
    } else {
      this.stepPatrol(time);
    }

    this.currentScale += (this.targetScale - this.currentScale) * 0.12;
    this.mesh.scale.setScalar(this.currentScale);

    this.currentTint.lerp(this.targetTint, 0.1);
    this.material.color.copy(this.currentTint);

    this.currentEmissive += (this.targetEmissive - this.currentEmissive) * 0.1;
    this.material.emissiveIntensity = this.currentEmissive;
  }

  stepPatrol(time) {
    const { spreadX } = this.layout;
    const angle = (time * 0.001 * Math.PI * 2) / PATROL_SECONDS + this.startAngle;

    // A flat loop in front of the constellation, not a vertical ring. Travelling a tall
    // ellipse pitched the hull through a whole turn every lap, which read as the ship
    // spinning on its own, and it put the heading parallel to the up reference at the
    // top and bottom of the loop, where the basis collapsed.
    const radiusX = spreadX * 1.15;
    const radiusZ = spreadX * 0.55;
    const depth = spreadX * 0.5;

    this.group.position.lerp(
      new THREE.Vector3(
        Math.cos(angle) * radiusX,
        Math.sin(angle * 2) * 4,
        depth + Math.sin(angle) * radiusZ,
      ),
      0.05,
    );

    // Level flight, banking into the turn. The heading stays horizontal, so it can never
    // fall parallel to world up.
    const heading = new THREE.Vector3(-Math.sin(angle) * radiusX, 0, Math.cos(angle) * radiusZ).normalize();
    const inward = new THREE.Vector3(-Math.cos(angle), 0, -Math.sin(angle));
    this.orient(heading, UP.clone().addScaledVector(inward, 0.2).normalize(), 0.07);
  }

  focusOn(planet) {
    const fromCenter = this.group.position.clone().sub(planet.group.position);
    this.focus = { planet, angle: Math.atan2(fromCenter.z, fromCenter.x) };
  }

  clearFocus() {
    this.focus = null;
  }

  stepOrbit(time) {
    const planet = this.focus.planet;
    const center = planet.group.position;
    const radius = orbitRadiusFor(planet, planet.currentScale || 1);
    const angle = (time * 0.001 * Math.PI * 2) / ORBIT_SECONDS + this.focus.angle;

    const offset = new THREE.Vector3(Math.cos(angle) * radius, 0, Math.sin(angle) * radius);
    offset.applyAxisAngle(new THREE.Vector3(1, 0, 0), ORBIT_TILT);
    this.group.position.lerp(offset.add(center), 0.06);

    const heading = new THREE.Vector3(-Math.sin(angle), 0, Math.cos(angle));
    heading.applyAxisAngle(new THREE.Vector3(1, 0, 0), ORBIT_TILT).normalize();
    const inward = new THREE.Vector3(-Math.cos(angle), 0, -Math.sin(angle));
    this.orient(heading, UP.clone().addScaledVector(inward, 0.28).normalize(), 0.07);
  }

  landOn(planet, onArrive) {
    if (this.landing) return false;

    const center = planet.group.position.clone();
    // The planet body renders at planet.radius * currentScale, so the hull must sit
    // against that swollen radius or it ends up buried inside the globe.
    const radius = planetFootprint(planet, planet.currentScale || 1);
    const normal = this.pickTouchdownNormal(center);

    const end = center.clone().addScaledVector(normal, Math.max(4, radius - SHIP_LENGTH * SURFACE_INSET));
    const approach = end.clone().addScaledVector(normal, radius * 0.85 + SHIP_LENGTH * 2.2);

    this.landing = {
      startedAt: performance.now(),
      from: this.group.position.clone(),
      control: this.group.position.clone().lerp(approach, 0.5).addScaledVector(normal, 9),
      approach,
      end,
      endQuaternion: new THREE.Quaternion().setFromUnitVectors(UP, normal),
      onArrive,
      settled: false,
    };

    return true;
  }

  pickTouchdownNormal(center) {
    // Touch down well off the camera axis so the hull is seen in profile against the
    // limb. Landing dead centre would point the nose straight at the viewer.
    const toCamera = new THREE.Vector3(0, 0.15, 1).normalize();
    const fromCenter = this.group.position.clone().sub(center);
    fromCenter.y = 0;

    const lateral = fromCenter.lengthSq() > 1 ? fromCenter.normalize() : new THREE.Vector3(1, 0, 0);
    lateral.addScaledVector(toCamera, -lateral.dot(toCamera));
    if (lateral.lengthSq() < 1e-6) lateral.set(1, 0, 0);
    lateral.normalize();

    const tilt = THREE.MathUtils.degToRad(55);
    return toCamera.clone().multiplyScalar(Math.cos(tilt)).addScaledVector(lateral, Math.sin(tilt)).normalize();
  }

  stepLanding(now) {
    const landing = this.landing;
    const elapsed = now - landing.startedAt;

    if (elapsed < FLY_MS) {
      const t = easeInOutCubic(elapsed / FLY_MS);
      const position = quadBezier(landing.from, landing.control, landing.approach, t);
      const ahead = quadBezier(landing.from, landing.control, landing.approach, Math.min(1, t + 0.02));
      this.group.position.copy(position);
      // Eased rather than snapped: a hard set here lurched the hull whenever the entry
      // heading differed a lot from the direction it had been flying.
      this.orient(ahead.sub(position), UP, 0.15);
      return;
    }

    if (elapsed < TOUCHDOWN_MS) {
      const t = easeOutCubic((elapsed - FLY_MS) / (TOUCHDOWN_MS - FLY_MS));
      this.group.position.lerpVectors(landing.approach, landing.end, t);
      this.group.quaternion.slerp(landing.endQuaternion, 0.12);
      return;
    }

    this.group.position.copy(landing.end);
    this.group.quaternion.copy(landing.endQuaternion);

    if (!landing.settled && elapsed >= HOLD_MS) {
      landing.settled = true;
      this.landing = null;
      if (landing.onArrive) landing.onArrive();
    }
  }
}
